transcendance/tournaments/urls.py
from django.urls import path
from . import views
app_name = "tournaments"

urlpatterns = [
    path('', views.TournamentListView.as_view(), name='index'),
    path('create/', views.create_tournament, name='create_tournament'),
    path('settings/<int:pk>', views.TournamentSettingsView.as_view(), name='tournament_settings'),
    path('tournament_detail/<int:pk>', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('<tournament_name>', views.show_tournament, name='show_tournament'),
]

transcendance/tournaments/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
# Create your models here.


# Create your models here.
class Tournament(models.Model):
    name = models.CharField(max_length=100, default='Great tournament')
    bio = models.TextField(default='Wonderfull tournament')
    over = models.BooleanField(default=False)
    public = models.BooleanField(default=False)
    
    number_players = models.PositiveIntegerField(default=4)
    players = models.ManyToManyField(User)
    
    @staticmethod
    def create_tournament(user):
        t = Tournament.objects.create()
        t.players.add(user)
        t.save()
        return t

    @property
    def player_count(self):
        return len(self.players)
    @property
    def is_full(self):
        return self.player_count == self.number_players
    

    def get_absolute_url(self):
        return reverse('tournaments:tournament_detail', args=[self.pk])
    
    def __str__(self) -> str:
        return f"{self.name}"
    # class Meta:

transcendance/tournaments/forms.py
from typing import Any
from django import forms
from .models import Tournament

class TournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = ['name', 'bio']
        
    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 3:
            raise forms.ValidationError("3 letter min")
        return name
    
    # def clean(self) -> dict[str, Any]:
    #     #form global rules
    #     return super().clean()

transcendance/tournaments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Tournament
from .forms import TournamentForm
from common.utils import get_context, get_form_context, get_optional_action_table_context, get_table_context
from django.contrib.auth.decorators import login_required
from common.utils import redir_to_index, redir_to
from typing import Any
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView
from .filters import TournamentFilter
from .tables import TournamentTable
from django.urls import reverse
from tournaments.abstract_views import TournamentView

app_name = 'tournaments'

def index(request):
    context = get_table_context(
        app_name=app_name,
        objects=Tournament.objects.all(),
        field='name',
        url_to_redir=f"{app_name}:show_tournament",
    )
    return render(request, f'{app_name}/index.html', context)



def show_tournament(request, tournament_name):
    tournament = get_object_or_404(Tournament,  name=tournament_name)
    context = get_table_context(app_name=app_name, objects=tournament.players.all(), url_to_redir='accounts:profil_detail', field='username')
    return render(request, f'{app_name}/tournament.html', context)




# @login_required
class TournamentSettingsView(UpdateView):
    model = Tournament
    fields = ['name', 'public', 'number_players']
    template_name = 'utils/form.html'
    
class TournamentDetailView(DetailView):
    model = Tournament
    template_name = 'tournaments/tournament_detail.html'
    
@login_required
def create_tournament(request):
    t = Tournament.create_tournament(request.user)
    return redirect(TournamentView(t).get_edit_url())
    
class TournamentListView(SingleTableMixin, FilterView):
    table_class = TournamentTable
    model = Tournament
    template_name = "tournaments/tournament_list.html"
    filterset_class = TournamentFilter

transcendance/tournaments/templates/tournaments/create_tournament.html
{% comment %} {% extends "utils/g_form.html" %} {% endcomment %}

{% comment %} 
context = {
    'form' : profile_form,
    'app_name' : app_name,
} 
{% endcomment %}

transcendance/tournaments/templates/tournaments/index.html
{% extends "utils/g_table.html" %}

{% comment %} 
context = {
        'objects': object_list_to_treat,
        'field': field_to_get,
        'redir': url_to_redir,
        'display': display_name_default_is_object
        'action_cond': action_cond_to_add_actions,
        'actions': {'name': 'redir',},
    } 
{% endcomment %}

{% block more_content %}
<li> <a href="{% url 'tournaments:create_tournament' %}"> add </a> </li>
{% endblock %}

transcendance/tournaments/templates/tournaments/tournament.html
{% extends "utils/base.html" %}

{% comment %} 
context = {
    'app_name' : app_name,
    'field' : 'field',
    'objects' : objects,
    
} 
{% endcomment %}
{% block content %}
{% include 'utils/g_hreflist.html' with field=field objects=objects%}
{% endblock %}

transcendance/tournaments/templates/tournaments/tournament_detail.html
{% extends 'utils/base.html' %}

{% block content %}
{{object}}
{% endblock%}

transcendance/tournaments/templates/tournaments/tournament_list.html
{% extends "utils/base.html" %}

{% block content %}
<p> <a href="{% url 'tournaments:create_tournament' %}"> Create tournament </a> </p>

{% load html_utils %}
{% include_filter_table table=table filter=filter %}

{% endblock %}